### ISSUE TITLE
ID3v2 Support

### ISSUE THREAD

**Issue by FahimF** [muhku/FreeStreamer#146]
Hi,

Thanks for the FreeStreamer library - it works great. However, I notice that the library will fetch meta data only if the mp3 file has ID3v1 tags. If the mp3 file has ID3v2 tags, no meta data is fetched at all. Would it be possible to add support for ID3v2 tags?

**Comment by mmcdole** [comment]
:+1: would love to have ID3v2 tag parsing (including embedded coverart). 

The OrigamiEngine supports this so it might serve as a useful example for parsing the ID3v2 metadata.
https://github.com/ap4y/OrigamiEngine

**Comment by muhku** [comment]
The parser currently supports ID3v2.3 tags (https://github.com/muhku/FreeStreamer/blob/master/astreamer/id3_parser.cpp#L140)

If you want to help with this one, Pull Requests are welcome.

**Comment by mmcdole** [comment]
Going to try my hand at submitting a PR for this.  Will report back with my progress.

**Comment by muhku** [comment]
Thanks @mmcdole

**Comment by mmcdole** [comment]
Also, while people are waiting on this, I wanted to let people know how we are using FreeStreamer and still pulling full ID3v2.3 tag info + CoverArt as a workaround right now.

We set an outputFile in the ```FSAudioStream``` object so that we are writing the MP3 to disk as we stream it.  

Then, we use AVFoundation's AVAsset metadata parsing to read information from the outputFile to retrieve this metadata.  We do this on two FS events:

1.  When the 'onMetadataAvailable' block fires, we create an AVAsset out of the outputFile, and attempt to retrieve metadata.
2.  When the 'playbackEnded' state change fires, we again attempt to create an AVAsset and read the metadata.

MP3's typically have their ID3v2 tags at the beginning of their files, but occasionally we run into files where it is at the end.  The two times we check above covers both of these cases.

This has been working pretty reliably for us:
![coverart](https://cloud.githubusercontent.com/assets/3767096/6028781/8dd1a30a-abb1-11e4-89d6-abf0a803a9b0.gif)

Here is an SO answer on parsing metadata from an AVAsset:
http://stackoverflow.com/a/25794580/2635

**Comment by muhku** [comment]
For the binary data (i.e. covert), we could use Base64 encoded blobs so that we don't need to change the existing metadata API. At the client side the Base64 encoded blobs can be decoded. A small performance hit but acceptable I think as the thumbnails should be quite small.

**Comment by muhku** [comment]
Basic cover art support added in 5349a316ed16ab4bb109ab8928c18f404f851aca

Will not handle all possible cases but at least JPEG files attached in iTunes should work.

**Comment by muhku** [comment]
Both ID3v2.2 and ID3v2.3 are supported including support for cover art (the APIC frame). I think we are running a bit out of the scope for this task, so let's create more specific tasks for supporting the spec.

**Comment by muhku** [comment]
FreeStreamer 2.12.10 or later required.
