### ISSUE TITLE
ERROR: AVAudioSession.mm:646: -[AVAudioSession setActive:withOptions:error:]: Deactivating an audio session that has running I/O. 

### ISSUE THREAD

**Issue by OliverDimitrov** [muhku/FreeStreamer#147]
Hi @muhku ,

I'm using FSAudioStream to play live and .mp3 streams. I hold the streamer in a singleton as I need it through the whole app.

So here is the scenario:
I play live stream, then decide to play the .mp3 stream without previously stopping the live stream.
The code snippet:
```Objective-C
- (void)playAudioWithUrlString:(NSString *)urlString
{
  if (![self.streamingURLString isEqualToString:urlString]) {
      self.streamingURLString = urlString;
//      if (self.audioStreamer.isPlaying) // It's not working!?
          [self.audioStreamer stop]
// start new player
//    [self performSelector:@selector(playNewURI:) withObject:urlString afterDelay:0.5]; // with this code works.
    self.audioStreamer.url = [NSURL URLWithString:self.streamingURLString];
    [self.audioStreamer play];
  } else {
    [self.audioStreamer pause];
  }
}
```
Then I get this error : 
**ERROR: AVAudioSession.mm:646: -[AVAudioSession setActive:withOptions:error:]: Deactivating an audio session that has running I/O. All I/O should be stopped or paused prior to deactivating the audio session.**

I guess this error is because the AVAudioSession needs some time to deactivate the session, because with the delay it works, but I don't fancy that way of doing it.

It's strange, because in the reverse order, first stream the .mp3 then the live stream, this code works as it should.

Also I've noticed that the "isPlaying" flag never is set to YES even when the streamer is playing.

So can you point me what I'm doing wrong?

Thanks in advance,
Oliver

**Comment by muhku** [comment]
Which streamer version are you using?

**Comment by OliverDimitrov** [comment]
@muhku 2.9.14 installed via Cocoapods

**Comment by dagobert-duck** [comment]
Can confirm this error. However, the BOOL `isPlaying` is set correctly.

**Comment by muhku** [comment]
I wouldn't recommend using singleton players. There can be potential cached data in memory, etc, which doesn't necessarily get released. But yeah, the AVAudioSession problem sounds like a problem. So:

1) isPlaying is an Objective-C method, not a property, so you need to call it accordingly. That's why self.audioStreamer.isPlaying doesn't work.

2) For the AVAudioSession problem, I could take a look if there's a *minimal* test case which reproduces it. The best would to add a new one to https://github.com/muhku/FreeStreamer/blob/master/FreeStreamerMobileTests/FreeStreamerMobileTests.m

**Comment by masterrr** [comment]
Yeah, also experiencing the running I/O issue.

**Comment by OliverDimitrov** [comment]
@muhku yeah, isPlaying is working correctly, but this problem with the AVAudioSession is driving me nuts.

At home I've updated to 2.9.16 and the same code worked flawlessly. I go to work, plug it in a device, run the same code, the AVAudioSession error appears again!.. It's very strange.

Tell me, what will happen if I don't call stop on the streamer when I try to play another file?
```Objective-C
  if (![self.streamingURLString isEqualToString:urlString]) {
    self.streamingURLString = urlString;
    self.audioStreamer = nil;
    self.audioStreamer = [[FSAudioStream alloc] init];
    self.audioStreamer.url = [NSURL URLWithString:self.streamingURLString];
    
    [self.audioStreamer play];
  }
  else {
    if (self.currentState == RNStatePlaying || self.currentState == RNStatePaused)
      [self.audioStreamer pause];
    else
      [self.audioStreamer play];
  }

```
This way it works, but I'm afraid that in background the sessions will remain open. Any thoughts?

**Comment by muhku** [comment]
@OliverDimitrov: You don't need to call stop explicitly. There's nothing magical in the code, if you see it yourself, it calls stop by itself if you change the URL (https://github.com/muhku/FreeStreamer/blob/master/Common/FSAudioStream.mm#L365)

The thing is the more you try to manage the playback state outside the player, the more trouble you will encounter. The player knows how to do the resource cleanup, etc. That's why actually it is a good way to set the streamer to nil, which will cleanup the resources. The demo app actually works in that way.

**Comment by OliverDimitrov** [comment]
Yeah, OK, it works for now = ) Feel free to close the issue if you like.

**Comment by davinder2292** [comment]
@muhku I am using this streamer.
In my case i had to stop streamer suddenly and start an audio recorder but when i stop the streamer, i am getting the issue mentioned above.
Is their is any fix for this problem because i have to start an audio session for recording too.

**Comment by syosan** [comment]
i call exit(0) in objective-c, it will cost 3's to exit my app, why?

**Comment by syosan** [comment]
ERROR: AVAudioSession.mm:646: -[AVAudioSession setActive:withOptions:error:]: Deactivating an audio session that has running I/O. All I/O should be stopped or paused prior to deactivating the audio session.

i call exit(0) in objective-c, it will cost 3's to exit my app,and print the error log, why?
