### ISSUE TITLE
Downloading only part of a stream

### ISSUE THREAD

**Issue by davidhlee** [muhku/FreeStreamer#179]
Is it possible to download only a portion of a stream? For instance, if the stream is 1 hour long, is it possible to download only a 20 second portion in the middle of the stream, instead of the entire stream--to avoid long wait times? 

If not, is it possible to crop and save a 20 second portion of a stream as an .m4a file without downloading the entire stream to a file on disk?

**Comment by muhku** [comment]
It is possible to start the download from a specific position (the server must support the HTTP byte range queries). Start the stream with [playFromOffset](http://freestreamer.io/api/Classes/FSAudioStream.html#//api/name/playFromOffset:). Then, when the 20 seconds portion has finished playback, stop the player. In this way a bit more data will be transferred but the user doesn't have to wait for so long.

**Comment by davidhlee** [comment]
Thanks! I'll give it a try.

**Comment by davidhlee** [comment]
Hi, so I know that playFromOffset is working with my particular stream, because in viewDidAppear: (FSPlayerViewController) in the example project, when _lastPlaybackURL exists, the stream successfully picks back up where it left off. 

However, when I try playFromOffset upon initial page load, the UISlider sets the position to 0.287300 correctly, but the stream still plays from the beginning. Do I have to wait for buffering to complete before calling playFromStream? If so, what event or notification should I be listening for?

```
if ([self.audioController.url isEqual:_lastPlaybackURL]) {
    // The same file was playing from a position, resume (THIS WORKS!)
    [self.audioController.activeStream playFromOffset:_lastSeekByteOffset];
} else {
    FSSeekByteOffset offset;
    offset.position = 0.287300;
    [self.audioController.activeStream playFromOffset:offset]; // THIS DOESN'T WORK
}
```

Alternatively, upon initial page load, should I try something like?: 
```
[self.audioController play];
            
FSStreamPosition pos;
pos.position = 0.287300;
[self.audioController.activeStream seekToPosition:pos];
```

**Comment by muhku** [comment]
I think FSSeekByteOffset in your case is missing the actual offset values (or they are actually 0, so playback begins from the beginning of the stream). So you need to figure out the HTTP byte range you want to request and then fill the correct values:

<pre>
FSSeekByteOffset offset;
offset.position = 0.287300;
offset.start = ... // the beginning of the HTTP byte range
offset.end = ... // the end of the HTTP byte range
</pre>

Then, calling FSAudioStream playFromOffset should work. If you have trouble figuring out the correct offset values, you could simply print out the values with the currentSeekByteOffset property, when you have reached the target point. So play the file and once you have reached the target position and call currentSeekByteOffset.

Btw, I recommend using FSAudioStream directly instead of FSAudioController if you don't need to have playlists or automatically resolve stream URLs. It will work faster and you'll get less HTTP traffic.

**Comment by davidhlee** [comment]
Setting the actual HTTP byte range worked! Thanks. 

Out of curiosity--when using playFromOffset instead of play, the stream loads MUCH faster, like several seconds faster, and even seeking is more seamless. Why is that? And if it's so much faster, why shouldn't one always use playFromOffset even when playing a stream from the beginning, and simply setting the offset.start and offset.position to something arbitrarily small so that the user doesn't notice?

What, if any, are the advantages of using play over playFromOffset?

**Comment by muhku** [comment]
Basically play should be used in most cases because it calculates buffer sizes based on the given configuration. Perhaps take a look at the FAQ for the possible buffering settings: https://github.com/muhku/FreeStreamer/wiki/FreeStreamer-FAQ

I'll close this one for now, as the original issue was solved.
