### ISSUE TITLE
Seek/jump in continuous stream

### ISSUE THREAD

**Issue by Djelibeybi** [muhku/FreeStreamer#181]
I apologise if this is the wrong place to ask implementation questions, so please direct me to a more suitable location if it exists.

I'm building an app that streams a single audio source, and allows that source to be paused or stopped. If a user has paused the source and then resumes playback, what's the best way to allow them to seek/jump forward until they hit the live source again?

I'm going to start playing with seeking, but I thought I'd ask in case there was an already tried-and-testing method.

**Comment by muhku** [comment]
Not sure if I understood what you want to achieve but I think something similar was asked before. The use case was that after pausing the stream had to stay "current", that is, not to play any cached content. The simple way is to stop the stream instead of pausing it. The more complex way would be to add a new method to flush the caches which you would call before resuming the playback from pause.

**Comment by Djelibeybi** [comment]
No, I have a different use case: I want to be able to pause the stream and on resume, allow the listener to jump forward through the cache until they hit the live stream again. Essentially, the listener resumes where they left off, but has the option of jumping forward (to skip ads or a song they don't like or similar).

**Comment by muhku** [comment]
Yep. I think that was exactly asked before :) So, it would mean adding a method for flushing the caches before resuming.

**Comment by Djelibeybi** [comment]
Almost - I don't want to flush the cache. I want to be able to seek through it, if that makes sense. For example, assume I pause for 60 seconds. When I resume, I have 60 seconds in the cache. I'd like the listener to be able to jump forward in the cache, in sections, e.g. in 10 or 20 seconds increments.

**Comment by muhku** [comment]
I think I understood it now. One thing to remember  though: 60 seconds of compressed audio is more than 60 seconds of non-compressed audio. Or, it could be that if the bandwidth is not enough (bad connection) the cache could even underflow and the stream needs to buffer again. Everything depends on the connection.

But, basically, you would want to add a method to advance the playback pointer in audio_stream.cpp. The method needs to calculate how many seconds of non-compressed audio a single compressed audio packet is and then increment the playback pointer with the desired amount of packets. There is some related code in seeking.

**Comment by Djelibeybi** [comment]
Exactly. Being able to jump backwards through the cache would be amazing, but not critical. Essentially, replicating what the TuneIn player can do, i.e. it allows you to rewind/fast-forward any audio that it has already played/cached (up to the limit of the cache, obviously).

**Comment by muhku** [comment]
Created a proof of concept patch: https://gist.github.com/muhku/9c97ab9e35ab7f4a8b19

You can try it by playing a stream and by pressing the pause button, it rewinds the stream. There can be still bugs but it should be enough to start experimenting.

**Comment by Djelibeybi** [comment]
The gist seems to trigger a stream rebuffer (and in some cases, just hangs on buffering). Actual buffering is exactly what this request is meant to avoid: if the cache already exists on the device (due to being paused for some amount of time), we want the ability to jump forwards or backwards within the cache. But these actions should never trigger a rebuffer. 

So, it should be limited by the amount of data in the cache, i.e. if you try to jump too far back, it just starts at the beginning of the cache and if you try to jump too far forward, it just returns to the live stream.

**Comment by musiclistener** [comment]
Hi there

I have also been trying really hard(to no avail) to get seeking working for a continuous stream - thus the ability to seek the cache(backwards in my case). I have tried your rewind method and it works perfectly for an mp3  on disk, unfortunately it does not work for a Live HTTP stream, it seems to jump forward in the stream instead of backwards.

I have tried numerous libraries, AVPlayer(you can seek backwards but there is a limited buffer, I need to seek back a couple of mins sometimes). Why is it so hard to seek continues stream cache? Seems nobody has nailed it yet.

**Comment by zhangshijian** [comment]
i have the  same problem  ,seek   ,   please help me   , i am getting Started    ，And my  English is bad, Thanks very much  .

**Comment by muhku** [comment]
Here's the proof-of-concept patch ported on FreeStreamer 3.x: https://gist.github.com/muhku/84de07490f37badda1dd

**Comment by muhku** [comment]
Pushed 7d231fe0c7daa7a2d1cb9aab68676dae30468b2b to master. Let me know if this works for you.

**Comment by muhku** [comment]
Pushed out in 3.0.13

http://muhku.github.io/FreeStreamer/api/Classes/FSAudioStream.html#//api/name/rewind:

**Comment by opiator** [comment]
Hi Mukhu

Thank you, I have managed to get the POC to work. I had to make 2 adjustments(will try and do PR if I have a better cache cleanup solution instead of just disabling it):

1.)
/* The only reason we keep the already converted packets in memory
         * is seeking from the cache. If in-memory seeking is disabled we
         * can just cleanup the cache immediately. The same applies for
         * continuous streams. They are never seeked backwards.
         */
if (!config->seekingFromCacheEnabled ||
            continuous ||
            THIS->m_cachedDataSize >= config->maxPrebufferedByteCount) {

The continuous flag needs to be removed, otherwise the cache will be cleared.

2.)
if (THIS->m_numPacketsToRewind > 0) {
        queued_packet_t *front = THIS->m_queuedHead;
        while (front && THIS->m_numPacketsToRewind-- > 0) {
            queued_packet_t *tmp = front->next;
            front = tmp;
        }    
        THIS->m_playPacket = front;
        THIS->m_numPacketsToRewind = 0;
    }

The front packet needs to be the queue head instead of the current playing packet, otherwise it will actually skip forward.
