### ISSUE TITLE
Change stream configuration while stream is running

### ISSUE THREAD

**Issue by Djelibeybi** [muhku/FreeStreamer#183]
I've created a singleton to handle the FSAudioStream across my entire app. However, the configuration settings are only set during init, which means I can't change things like the bounceInterval or maxBounceCount after the singleton has been initiated. 

It would be really handy if these values could be changed after init, even if it requires stopping and starting the stream again.

**Comment by muhku** [comment]
Well, this is one of the problems with singletons. I would actually recommend creating streamer instances when needed instead of a single global instance. It also helps with the memory management (caches free'd when you release the streamer when not needing it).

So not very enthusiastic for changing the immutable configuration but if you got some ideas, pull requests can be always submitted and I can review.
