### ISSUE TITLE
Song restarting half way through

### ISSUE THREAD

**Issue by corymsmith** [muhku/FreeStreamer#250]
Had lots of reports of this happening as well.

This was using 3.0.21 I believe.

**Comment by muhku** [comment]
Any error logs?

**Comment by corymsmith** [comment]
I'll do some debugging and try to get some logs, I've never seen the issue myself but had lots of reports from users.

**Comment by muhku** [comment]
I think this could be improved by making HTTP_Stream to try to reopen the connection instead of signaling an error to the delegate in case of a non-continuous stream. HTTP_Stream should keep track of bytes received and if connection drops, it should try to reopen the connection from the last byte offset. In this way the stream could gracefully recover instead of failing. If somebody wants to submit a PR for this, I can advice the details more but should be manageable to implement :)

**Comment by corymsmith** [comment]
Any details you can add would help and if I have some time I can try to do a PR

**Comment by muhku** [comment]
1. The number of bytes received should be tracked here: https://github.com/muhku/FreeStreamer/blob/master/astreamer/http_stream.cpp#L786 Add a new member variable which keeps track of the bytes received. Reset the number of bytes received when the connection is opened with open()

2. If read fails and the we are streaming a non-continuous stream (m_contentLength > 0), instead of calling the delegate with streamErrorOccurred(), try reopening the stream with open() and supply Input_Stream_Position formed with the number of bytes of received.

This is the essential of the logic. There might be corner cases but this should be already good enough for a POC.

**Comment by muhku** [comment]
Automatic recovery added. In case HTTP connection fails for a non-continuous stream and the connection can be reopened without errors, the streaming continues without an interruption.

Change done in v3.5.2.
